spring.application.name: cache-demo
server:
  port: 5001
management:
  security:
    enabled: false
    
spring:
  autoconfigure:
    exclude:
      -     org.springframework.boot.autoconfigure.cache.CacheAutoConfiguration
      